SRCS = lval.c builtins_funcs.c builtins_sums.c eval.c lenv.c prompt.c utils.c tokeniser.c reader.c

BIN1 = lilith
BIN1_SRCS = $(SRCS)
BIN1_BLOBS = stdlib.llth
LIBS = -ledit -lm

include ../lib/simplified-make/simplified.mk
